### ISSUE TITLE
Update `unexported-airnode-features`

### ISSUE THREAD

**Issue by metobom** [api3dao/signed-api#79]
Pusher uses an old version of `processing`  for pre/post-processing under `unexported-airnode-features` folder. We need [this](https://github.com/api3dao/airnode/pull/1831) feature from Airnode 0.12.0.

Possibly related to #77

**Comment by Siegrift** [comment]
I can finish https://github.com/api3dao/commons/pull/9 which we can then release and then merge https://github.com/api3dao/signed-api/pull/75.

I think we can do the above tomorrow, so that should be fine?

**Comment by bdrhn9** [comment]
Fwiw, in the concept implementation I created this pre/post functions externally not for they are unexported but to implement requested feature. It's [here](https://github.com/nodaryio/signed-data-pusher/blob/d7375554733a334f8b2dde7315ca7b5ef057a174/src/make-request.ts#L69) paremeters are also passed to post-processing. So, the example config generated by Nodary won't work because we are leveraging parameters in post processing, see https://github.com/api3dao/signed-api/blob/main/packages/pusher/config/pusher.example.json#L82.

**Comment by Siegrift** [comment]
Yeah, but this was later already [implemented in Airnode](https://github.com/api3dao/airnode/pull/1831). You can see that the [pusher config](https://github.com/api3dao/signed-api/blob/4138fa9977009a899fe1a42af5ad41983d13704a/packages/pusher/config/pusher.example.json#L82) the same as the Nodary one and I checked that it works.
